# .goreleaser.yaml
version: 2

project_name: flavour-gen

before:
  hooks:
    - go mod tidy

builds:
  - id: flavour-gen
    binary: flavour-gen
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/ZenDeveloper7/flavour-gen/cmd.Version={{.Version}}
      - -X github.com/ZenDeveloper7/flavour-gen/cmd.BuildTime={{.Date}}
      - -X github.com/ZenDeveloper7/flavour-gen/cmd.GitCommit={{.Commit}}

archives:
  - id: default
    format: tar.gz

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: ZenDeveloper7
    name: flavour-gen
